baseurl = "https://example.org/"
title = "Olivia Jo Bradley's Portfolio"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "Describe your website"
  copyright = "&copy;2024 Olivia Jo Bradley"
  sidebarAbout = [
    '''<img src="/img/about.jpg" alt="Personal Photo"> <br> Hello! I’m Olivia Jo, I'm a mechatronic engineer who loves learning new skills. 
    I graduated from Olin College of Engineering with a B.S. in Engineering with a 
    concentration in Robotics. I'm passionate about mechatronics, autonomous systems,
    renewable energy, and sustainability! Check out a few of my projects!'''
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "o.bradley@icloud.com"


  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "about/"
  home = true

  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Experience"
  url = "experience/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "o.bradley@icloud.com"
  linkedin      = "https://www.linkedin.com/in/oliviajobradley/"
  github        = "https://github.com/oliviajobradley"
